version: 2

jobs:
  "build-7.1":
    docker:
      - image: circleci/php:7.1-cli
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "Build"
          command: |
            phpize
            ./configure --enable-scoutapm
            make
      - run:
          name: "Run tests"
          command: |
            php run-tests.php -p `which php` -d zend_extension=`pwd`/modules/scoutapm.so -g "FAIL,XFAIL,BORK,WARN,LEAK,SKIP" --offline --show-diff --set-timeout 120
      - run:
          name: "Benchmark"
          command: |
            sudo apt update && sudo apt install time
            ./benchmark.sh
            ./benchmark.sh -w
      - store_artifacts:
          path: ~/repo/tests
  "build-7.2":
    docker:
      - image: circleci/php:7.2-cli
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "Build"
          command: |
            phpize
            ./configure --enable-scoutapm
            make
      - run:
          name: "Run tests"
          command: |
            php run-tests.php -p `which php` -d zend_extension=`pwd`/modules/scoutapm.so -g "FAIL,XFAIL,BORK,WARN,LEAK,SKIP" --offline --show-diff --show-slow 1000 --set-timeout 120
      - run:
          name: "Benchmark"
          command: |
            sudo apt update && sudo apt install time
            ./benchmark.sh
            ./benchmark.sh -w
  "build-7.3":
    docker:
      - image: circleci/php:7.3-cli
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "Build"
          command: |
            phpize
            ./configure --enable-scoutapm
            make
      - run:
          name: "Run tests"
          command: |
            php run-tests.php -p `which php` -d zend_extension=`pwd`/modules/scoutapm.so -g "FAIL,XFAIL,BORK,WARN,LEAK,SKIP" --offline --show-diff --show-slow 1000 --set-timeout 120
      - run:
          name: "Benchmark"
          command: |
            sudo apt update && sudo apt install time
            ./benchmark.sh
            ./benchmark.sh -w

workflows:
  version: 2
  build:
    jobs:
      - "build-7.1"
      - "build-7.2"
      - "build-7.3"
